const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    SWITCH_LANGUAGE_OF_WEBSITE: 'SWITCH_LANGUAGE_OF_WEBSITE',
    //user,
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',


    // Redux-getGender-(6): khai báo actiontypes
    //admin redux
    FETCH_GENDER_VALUE_START: 'FETCH_GENDER_VALUE_START',
    FETCH_GENDER_VALUE_SUCCESSFULLY: 'FETCH_GENDER_VALUE_SUCCESSFULLY',
    FETCH_GENDER_VALUE_FAILED: 'FETCH_GENDER_VALUE_FAILED',
    // Redux-getGender-(7): khai báo xong thì tạo một reducer adminReducer


    FETCH_POSITION_VALUE_START: 'FETCH_GENDER_VALUE_START',
    FETCH_POSITION_VALUE_SUCCESSFULLY: 'FETCH_POSITION_VALUE_SUCCESSFULLY',
    FETCH_POSITION_VALUE_FAILED: 'FETCH_POSITION_VALUE_FAILED',

    FETCH_ROLE_VALUE_START: 'FETCH_GENDER_VALUE_START',
    FETCH_ROLE_VALUE_SUCCESSFULLY: 'FETCH_ROLE_VALUE_SUCCESSFULLY',
    FETCH_ROLE_VALUE_FAILED: 'FETCH_ROLE_VALUE_FAILED',

    //add new user using redux
    //tạo redux getPosition và role không theo chuẩn redux: có 2 case là success và fail thôi
    //không có case start
    ADD_NEW_USER_SUCCESSFULLY: 'SAVE_USER_SUCCESSFULLY',
    ADD_NEW_USER_FAILED: 'SAVE_USER_FAILED',

    //action lấy dữ liệu user từ redux để cho vào bảng displayRedux, (menu 1 option 2)
    FETCH_ALL_USERS_VALUE_SUCCESSFULLY: 'FETCH_ALL_USERS_VALUE_SUCCESSFULLY',
    FETCH_ALL_USERS_VALUE_FAILED: 'FETCH_ALL_USERS_VALUE_FAILED',
    // xóa user bằng redux
    DELETE_USER_SUCCESSFULLY: 'DELETE_USER_SUCCESSFULLY',
    DELETE_USER_FAILED: 'DELETE_USER_FAILED',
    //edit bằng redux
    EDIT_USER_SUCCESSFULLY: 'EDIT_USER_SUCCESSFULLY',
    EDIT_USER_FAILED: 'EDIT_USER_FAILED',
    //lấy dữ liệu các bác sĩ nổi bật
    FETCH_ELITE_DOCTORS_VALUE_SUCCESSFULLY: 'FETCH_ELITE_DOCTORS_VALUE_SUCCESSFULLY',
    FETCH_ELITE_DOCTORS_VALUE_FAILED: 'FETCH_ELITE_DOCTORS_VALUE_FAILED',
    //lấy dữ liệu các bác sĩ cho tùy chọn bác sĩ ở trang doctorArticle
    GET_All_DOCTORS_FOR_DOCTOR_ARTICLE_PAGE_SUCCESSFULLY: 'GET_All_DOCTORS_FOR_DOCTOR_ARTICLE_PAGE_SUCCESSFULLY',
    GET_All_DOCTORS_FOR_DOCTOR_ARTICLE_PAGE_FAILED: 'GET_All_DOCTORS_FOR_DOCTOR_ARTICLE_PAGE_FAILED',
    //lưu thông tin giới thiệu và bài báo về một bác sĩ
    SAVE_INFOR_AND_ARTICLE_FOR_A_DOCTOR_SUCCESSFULLY: 'SAVE_INFOR_AND_ARTICLE_FOR_A_DOCTOR_SUCCESSFULLY',
    SAVE_INFOR_AND_ARTICLE_FOR_A_DOCTOR_FAILED: 'SAVE_INFOR_AND_ARTICLE_FOR_A_DOCTOR_FAILED',
})

export default actionTypes;