const actionTypes = Object.freeze({
  //app
  APP_START_UP_COMPLETE: "APP_START_UP_COMPLETE",
  SET_CONTENT_OF_CONFIRM_MODAL: "SET_CONTENT_OF_CONFIRM_MODAL",
  SWITCH_LANGUAGE_OF_WEBSITE: "SWITCH_LANGUAGE_OF_WEBSITE",
  //user,
  ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
  PROCESS_LOGOUT: "PROCESS_LOGOUT",

  // Redux-getGender-(6): khai báo actiontypes
  //admin redux
  FETCH_GENDER_VALUE_START: "FETCH_GENDER_VALUE_START",
  FETCH_GENDER_VALUE_SUCCESSFULLY: "FETCH_GENDER_VALUE_SUCCESSFULLY",
  FETCH_GENDER_VALUE_FAILED: "FETCH_GENDER_VALUE_FAILED",
  // Redux-getGender-(7): khai báo xong thì tạo một reducer adminReducer

  FETCH_POSITION_VALUE_START: "FETCH_GENDER_VALUE_START",
  FETCH_POSITION_VALUE_SUCCESSFULLY: "FETCH_POSITION_VALUE_SUCCESSFULLY",
  FETCH_POSITION_VALUE_FAILED: "FETCH_POSITION_VALUE_FAILED",

  FETCH_ROLE_VALUE_START: "FETCH_GENDER_VALUE_START",
  FETCH_ROLE_VALUE_SUCCESSFULLY: "FETCH_ROLE_VALUE_SUCCESSFULLY",
  FETCH_ROLE_VALUE_FAILED: "FETCH_ROLE_VALUE_FAILED",

  //add new user using redux
  //tạo redux getPosition và role không theo chuẩn redux: có 2 case là success và fail thôi
  //không có case start
  ADD_NEW_USER_SUCCESSFULLY: "SAVE_USER_SUCCESSFULLY",
  ADD_NEW_USER_FAILED: "SAVE_USER_FAILED",

  //action lấy dữ liệu user từ redux để cho vào bảng displayRedux, (menu 1 option 2)
  FETCH_ALL_USERS_VALUE_SUCCESSFULLY: "FETCH_ALL_USERS_VALUE_SUCCESSFULLY",
  FETCH_ALL_USERS_VALUE_FAILED: "FETCH_ALL_USERS_VALUE_FAILED",
  // xóa user bằng redux
  DELETE_USER_SUCCESSFULLY: "DELETE_USER_SUCCESSFULLY",
  DELETE_USER_FAILED: "DELETE_USER_FAILED",
  //edit bằng redux
  EDIT_USER_SUCCESSFULLY: "EDIT_USER_SUCCESSFULLY",
  EDIT_USER_FAILED: "EDIT_USER_FAILED",
  //lấy dữ liệu các bác sĩ nổi bật
  FETCH_ELITE_DOCTORS_VALUE_SUCCESSFULLY:
    "FETCH_ELITE_DOCTORS_VALUE_SUCCESSFULLY",
  FETCH_ELITE_DOCTORS_VALUE_FAILED: "FETCH_ELITE_DOCTORS_VALUE_FAILED",
  //lấy dữ liệu các bác sĩ cho tùy chọn bác sĩ ở trang doctorArticle
  GET_All_DOCTORS_FOR_DOCTOR_ARTICLE_PAGE_SUCCESSFULLY:
    "GET_All_DOCTORS_FOR_DOCTOR_ARTICLE_PAGE_SUCCESSFULLY",
  GET_All_DOCTORS_FOR_DOCTOR_ARTICLE_PAGE_FAILED:
    "GET_All_DOCTORS_FOR_DOCTOR_ARTICLE_PAGE_FAILED",
  //lưu thông tin giới thiệu và bài báo về một bác sĩ
  SAVE_INFOR_AND_ARTICLE_FOR_A_DOCTOR_SUCCESSFULLY:
    "SAVE_INFOR_AND_ARTICLE_FOR_A_DOCTOR_SUCCESSFULLY",
  SAVE_INFOR_AND_ARTICLE_FOR_A_DOCTOR_FAILED:
    "SAVE_INFOR_AND_ARTICLE_FOR_A_DOCTOR_FAILED",
  //lấy thông tin doctor gồm description và article cho trang doctorManage
  FETCH_DOCTOR_DETAILS_FOR_DOCTOR_MANAGE_PAGE_SUCCESSFULLY:
    "FETCH_DOCTOR_DETAILS_FOR_DOCTOR_MANAGE_PAGE_SUCCESSFULLY",
  FETCH_DOCTOR_DETAILS_FOR_DOCTOR_MANAGE_PAGE_FAILED:
    "FETCH_DOCTOR_DETAILS_FOR_DOCTOR_MANAGE_PAGE_FAILED",
  //lấy khung giờ để bác sĩ hoặc bệnh nhân chọn
  FETCH_HOURS_IN_ALLCODES_FOR_SCHEDULE_MANAGE_PAGE_SUCCESSFULLY:
    "FETCH_HOURS_IN_ALLCODES_FOR_SCHEDULE_MANAGE_PAGE_SUCCESSFULLY",
  FETCH_HOURS_IN_ALLCODES_FOR_SCHEDULE_MANAGE_PAGE_FAILED:
    "FETCH_HOURS_IN_ALLCODES_FOR_SCHEDULE_MANAGE_PAGE_FAILED",
  //lưu timeframes cho một schedule khám bệnh của bác sĩ
  CREATE_TIMEFRAMES_FOR_DOCTOR_SCHEDULE_SUCCESSFULLY:
    "CREATE_TIMEFRAMES_FOR_DOCTOR_SCHEDULE_SUCCESSFULLY",
  CREATE_TIMEFRAMES_FOR_DOCTOR_SCHEDULE_FAILED:
    "CREATE_TIMEFRAMES_FOR_DOCTOR_SCHEDULE_FAILED",

  //lấy dữ liệu price, paymentMethod, province,.. từ Doctor_infor table cho trang doctormanage
  GET_REQUIRED_DATA_FOR_DOCTOR_MANAGE_PAGE_START:
    "GET_REQUIRED_DATA_FOR_DOCTOR_MANAGE_PAGE_START",
  GET_REQUIRED_DATA_FOR_DOCTOR_MANAGE_PAGE_SUCCESSFULLY:
    "GET_REQUIRED_DATA_FOR_DOCTOR_MANAGE_PAGE_SUCCESSFULLY",
  GET_REQUIRED_DATA_FOR_DOCTOR_MANAGE_PAGE_FAILED:
    "GET_REQUIRED_DATA_FOR_DOCTOR_MANAGE_PAGE_FAILED",

  //lây dữ liệu speacilties cho trang homePage
  FETCH_SPECIALTIES_VALUE_SUCCESSFULLY: "FETCH_SPECIALTIES_VALUE_SUCCESSFULLY",
  FETCH_SPECIALTIES_VALUE_FAILED: "FETCH_SPECIALTIES_VALUE_FAILED",

  //lưu dữ liệu tạm thời cho trang register để chuyển hướng sang trang yêu cầu thêm thông tin của người dùng
  SAVE_USER_EMAIL_AND_PASSWORD_TEMPORARILY_SUCCESSFULLY:
    "SAVE_USER_EMAIL_AND_PASSWORD_TEMPORARILY_SUCCESSFULLY",
  SAVE_USER_EMAIL_AND_PASSWORD_TEMPORARILY_FAIL:
    "SAVE_USER_EMAIL_AND_PASSWORD_TEMPORARILY_FAIL",

  //lấy tất cả thông tin liên quan của người dùng hệ thống hiện tại trong database
  GET_ALL_RELATIVE_INFOR_OF_CURRENT_SYSTEM_USER_SUCCESSFULLY:
    "GET_ALL_RELATIVE_INFOR_OF_CURRENT_SYSTEM_USER_SUCCESSFULLY",
  GET_ALL_RELATIVE_INFOR_OF_CURRENT_SYSTEM_USER_FAILED:
    "GET_ALL_RELATIVE_INFOR_OF_CURRENT_SYSTEM_USER_FAILED",

  //lấy thông tin ngắn gọn của các cơ sở y tế
  GET_BRIEF_INFO_OF_MEDICAL_FACILITY_SUCCESSFULLY:
    "GET_BRIEF_INFO_OF_MEDICAL_FACILITY_SUCCESSFULLY",
  GET_BRIEF_INFO_OF_MEDICAL_FACILITY_FAILED:
    "GET_BRIEF_INFO_OF_MEDICAL_FACILITY_FAILED",

  //lấy thông tin cơ sở y tế, chuyên khoa, giá cho một gói khám
  GET_ALL_RELATIVE_INFOR_FOR_A_EXAM_PACKAGE_SUCCESSFULLY:
    "GET_ALL_RELATIVE_INFOR_FOR_A_EXAM_PACKAGE_SUCCESSFULLY",
  GET_ALL_RELATIVE_INFOR_FOR_A_EXAM_PACKAGE_FAIL:
    "GET_ALL_RELATIVE_INFOR_FOR_A_EXAM_PACKAGE_FAIL",

  //lấy tất cả các Gói khám
  GET_ALL_EXAM_PACKAGE_SUCCESFULLY: "GET_ALL_EXAM_PACKAGE_SUCCESFULLY",
  GET_ALL_EXAM_PACKAGE_FAIL: "GET_ALL_EXAM_PACKAGE_FAIL",

  //lưu các khung giờ khám cho một Gói khám
  CREATE_TIMEFRAMES_FOR_PACKAGE_SUCCESSFULLY:
    "CREATE_TIMEFRAMES_FOR_PACKAGE_SUCCESSFULLY",
  CREATE_TIMEFRAMES_FOR_PACKAGE_FAILED: "CREATE_TIMEFRAMES_FOR_PACKAGE_FAILED",

  //tìm kiếm doctor, specialty, exam package, medical facility
  ALL_MEDICAL_SERVICE_FILTER_SEARCH_SUCCESSFULLY:
    "ALL_MEDICAL_SERVICE_FILTER_SEARCH_SUCCESSFULLY",
  ALL_MEDICAL_SERVICE_FILTER_SEARCH_FAILED:
    "ALL_MEDICAL_SERVICE_FILTER_SEARCH_FAILED",
});

export default actionTypes;
